title: Fuchen Chen
email: iicfcii@gmail.com
description: This is Fuchen Chen's personal website.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://iicfcii.github.io # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
domain: iicfcii.github.io
theme: jekyll-theme-minimal
